// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

type AuthResponse struct {
	User *ReturnUserFields `json:"user"`
}

type CreateCategoryInput struct {
	Image *string `json:"image,omitempty"`
	Name  string  `json:"name"`
}

type CreateColorInput struct {
	ImageCSS string `json:"imageCss"`
	Name     string `json:"name"`
}

type CreateInsolationInput struct {
	Name string `json:"name"`
}

type CreateOrderInput struct {
	Items []*OrderItemDto `json:"items"`
}

type CreateProductInput struct {
	CategorySlug string   `json:"categorySlug"`
	Colors       []string `json:"colors"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Insolation   string   `json:"insolation"`
	Name         string   `json:"name"`
	News         *bool    `json:"news,omitempty"`
	Price        int      `json:"price"`
	ProductColor string   `json:"productColor"`
	Sellers      *bool    `json:"sellers,omitempty"`
	Size         []string `json:"size"`
}

type CreateSizeInput struct {
	Name string `json:"name"`
}

type DeleteInsolationInput struct {
	Name string `json:"name"`
}

type GetAllProductInput struct {
	CategoryID             *string  `json:"categoryId,omitempty"`
	ColorID                *float64 `json:"colorId,omitempty"`
	GetProductByInsulation *float64 `json:"getProductByInsulation,omitempty"`
	MaxPrice               *string  `json:"maxPrice,omitempty"`
	MinPrice               *string  `json:"minPrice,omitempty"`
	NewProduct             *bool    `json:"newProduct,omitempty"`
	Page                   *string  `json:"page,omitempty"`
	PerPage                *string  `json:"perPage,omitempty"`
	SearchTerm             *string  `json:"searchTerm,omitempty"`
	Seller                 *bool    `json:"seller,omitempty"`
	Sort                   *string  `json:"sort,omitempty"`
}

type GetCategoryByIDInput struct {
	ID int `json:"id"`
}

type GetProductByColor struct {
	ColorID int    `json:"colorId"`
	Slug    string `json:"slug"`
}

type GetProductByID struct {
	ID int `json:"id"`
}

type Insolation struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type LoginInput struct {
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

type Mutation struct {
}

type NewTokensResponse struct {
	RefreshToken string            `json:"refreshToken"`
	User         *ReturnUserFields `json:"user"`
}

type OrderItemDto struct {
	Price        int    `json:"price"`
	ProductColor string `json:"productColor"`
	ProductID    int    `json:"productId"`
	ProductName  string `json:"productName"`
	Quantity     int    `json:"quantity"`
	Size         string `json:"size"`
}

type Product struct {
	CategoryID     int             `json:"categoryId"`
	Colors         []*ReturnColors `json:"colors"`
	Description    string          `json:"description"`
	ID             int             `json:"id"`
	Images         []string        `json:"images"`
	InsulationID   int             `json:"insulationId"`
	Name           string          `json:"name"`
	Price          int             `json:"price"`
	ProductColorID int             `json:"productColorId"`
	Size           []*Size         `json:"size"`
	Slug           string          `json:"slug"`
}

type ProductColor struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type ProductColorInput struct {
	Name string `json:"name"`
}

type ProductFiled struct {
	CategoryID int    `json:"categoryId"`
	ID         int    `json:"id"`
	Name       string `json:"name"`
}

type Query struct {
}

type ResponseCategory struct {
	ID    int    `json:"id"`
	Image string `json:"image"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
}

type ReturnColors struct {
	ID       int             `json:"id"`
	ImageCSS string          `json:"imageCss"`
	Name     string          `json:"name"`
	Products []*ProductFiled `json:"products"`
	Slug     string          `json:"slug"`
}

type ReturnFieldByCreateProduct struct {
	CategoryID  int      `json:"categoryId"`
	Description string   `json:"description"`
	ID          int      `json:"id"`
	Images      []string `json:"images"`
	Name        string   `json:"name"`
	Price       int      `json:"price"`
	Slug        string   `json:"slug"`
}

type Size struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateCategoryInput struct {
	ID    int     `json:"id"`
	Image *string `json:"image,omitempty"`
	Name  string  `json:"name"`
}

type UpdateInsolationInput struct {
	Name string `json:"name"`
}

type UpdateUserProfileInput struct {
	AvatarPath *string `json:"avatarPath,omitempty"`
	Email      string  `json:"email"`
	Name       *string `json:"name,omitempty"`
	Password   string  `json:"password"`
}

type User struct {
	AvatarPath string `json:"avatarPath"`
	Email      string `json:"email"`
	ID         int    `json:"id"`
	IsAdmin    bool   `json:"isAdmin"`
	Name       string `json:"name"`
	Password   string `json:"password"`
}

type AllProductsAndLength struct {
	Length   int        `json:"length"`
	Products []*Product `json:"products"`
}

type ReturnUserFields struct {
	Email   string `json:"email"`
	ID      int    `json:"id"`
	IsAdmin bool   `json:"isAdmin"`
}
